name: pi-fancontrol
base: core18
version: "0.2"
summary: Control a raspberry pi fan attached to a GPIO
description: |
  Control a fan attached to a GPIO via NPN transistor
  (defaults to GPIO 14 (pin 8))

  MAke sure to connect the snap interface for the correct GPIO
  that your fan is attached to (see https://pinout.xyz for correct mapping)

      snap connect pi-fancontrol:gpio pi:bcm-gpio-14

  To read temperatures you also need to connect the hardware-observe interface

      snap connect pi-fancontrol:hardware-observe

  The snap allows a few configurations to be set

  Pick a different GPIO to switch the fan on/off (do not forget to use the
  above connect command to enable access to this changed GPIO)

      snap set pi-fancontrol gpio=23

  Set the temperature threshold (in degrees celsius) at which the
  fan turns on

      snap set pi-fancontrol threshold=40

  Set the interval (in seconds) at which the temperature gets scanned

      snap set pi-fancontrol interval=60

grade: stable
confinement: strict
architectures:
  - build-on: armhf
    run-on: armhf
  - build-on: arm64
    run-on: arm64

apps:
  pi-fancontrol:
    command: fancontrol.sh
    daemon: simple
    plugs:
      - gpio
      - hardware-observe

parts:
  fancontrol:
    plugin: nil
    source: .
    override-build: |
      cp -av fancontrol.sh $SNAPCRAFT_PART_INSTALL/
